* Application
:PROPERTIES:
:TOC:      :include descendants
:END:
This document provides an overview of the files in the `application` directory, their purpose, and finer points of their use.  Most of these files are not intended to be changed, and editing these classes too much may have some unintended consequences on other code (read as "if you change the wrong thing in some of these files, the rest of the project /will/ crash unexpectedly").

:CONTENTS:
- [[#__init__py][_init_.py]]
- [[#configpy][config.py]]
- [[#loggerpy][logger.py]]
  - [[#usage][Usage]]
- [[#logviewpy][logview.py]]
  - [[#usage][Usage]]
- [[#performance_profilepy][performance_profile.py]]
  - [[#usage][Usage]]
:END:


** __init__.py
This file is used to mark the directory as a Python package. It is currently empty.

** config.py
This file contains the configuration management for the application.
- *Purpose:* Manages the application's configuration settings stored in a JSON file.
- *Key Functions:*
  - =load_config=: Loads the configuration from a file, creating an empty file if it doesn't exist.
  - =save_config=: Saves the configuration to a file.
  - =get_value=: Retrieves a configuration value based on a dot-separated key path.
  - =set_value=: Sets or updates a configuration value based on a dot-separated key path.
  - =remove_key=: Removes a specific key from the configuration.
  - =remove_section=: Removes an entire section from the configuration.

** logger.py
This file sets up logging for the application.
- *Purpose:* Provides logging capabilities with both file and console output.

*** Usage
Not intended for interactive use. If you wish to alter the functionality of the logging this project already performs, look into python [[https://docs.python.org/3/library/logging.html][logging]] library. To use in a new class, use a setup something like this:
#+begin_src python
  from application.logger import Logger

  class TEST:
      def __init__():
          self.logger = Logger(__name__).get()
          # Or, if you want to change the file that the class logs to
          self.logger = Logger(__name__, file_prefix="new_prefix").get()

      def test_log():
          self.logger.info({
              "event": "test_event_logged",
              "message": "This gets printed to STDOUT",
              "data": {
                  "any": "extra",
                  "data": "you",
                  "want": "to_log"
                  }
              })

          self.logger.debug({
              "event": "no_stdout",
              "data": {
                  "without": "the",
                  "message": "field",
                  "nothing": "gets_printed",
                  "to": "stdout"
                  }
              })

          self.logger.warning({
              "message": "Without the event field, nothing gets saved to a log file."
              "data": {
                  "This_extra": "data_is",
                  "largely": "useless_in",
                  "that": "case"
                  }
              })
#+end_src
** logview.py
This file provides a GUI application for viewing and filtering logs.
- *Purpose:* Allows users to view and filter log files generated by the application.


*** Usage
Run =python logview.py= (or the equivalent command for your virtual environment).

** performance_profile.py
This file provides a script for profiling the performance of other scripts.
- *Purpose:* Profiles the performance of a specified script using the =pyinstrument= library.


By default, will run the "wrapper.py" file in the root project directory. Edit as needed, but should not really need to profile anything else.

*** Usage
Run =python performance_profile.py= (or the equivalent command for your virtual environment).
