* CGSAR_RL

This project is an exploration of Reinforcement Learning (RL) concepts as they apply to U.S. Coast Guard Search and Rescue (SAR).

#+begin_quote
- [[#CGSAR_RL][CGSAR_RL]]
- [[#Background][Background]]
- [[#Project Structure][Project Structure]]
  - [[#Application][Application]]
  - [[#Simulation][Simulation]]
  - [[#Control][Control]]
  - [[#Resources][Resources]]
  - [[#Tests][Tests]]
#+end_quote

* Background

...

* Project Structure
** Application
This package handles application level configuration and logging In the future, if we reach the point where we create a GUI or some form of desktop application to interface with the rest of the project, it will be placed in this module. For now, the application package is home to two primary classes:

- =config.py=

  Defines the 'Config' class, which most other packages and classes use to read, write, and interact with a central JSON configuration file.

- =logger.py=

  Defines the 'Logger' class, which most other classes in this project use to save and display log messages. These logs are written to STDOUT as well as external log files, which are stored in the 'data/logs' directory.


This module also contains two standalone scripts, which are used primarily for debugging.
- =logview.py=

  Displays a simple tkinter window that should be helpful for perusing log files produced by this project.

- =performance_profile.py=

  Runs a simple wrapper around the simulation's =wrapper.py= file. Intended to profile the simulation environment, and has nothing to do with the RL portion of this project. Serves as a quick analysis of runtime complexity for the physical simulation environment.

** Simulation
This package is the most complex portion of the project, and is intended to serve as a simulation environment within which to run an RL agent. There are a variety of classes defined here, with the =Simulation= class serving as the main entry point.

- =Simulation.py=

  The main entry point to the =simulation= package. Wraps calls to the =Environment= and =VictimGroup= classes to define an ocean environment  with surface currents, wind, and a group of 'people' drifting in the water.

- =Environment.py=

  This class handles the environmental data, wrapping calls to =CurrentFetcher.py=, =DepthFetcher.py=, and =WindFetcher.py= to pull and store currents, wind, and depth data. This information is stored in =xarray= datasets.

- =VictimGroup.py=

  This class represents a group of 'victims', or people in the water, handling their motion through the water and their distribution in space.


These three classes serve as the main components of the =simulation= package. There are other classes within this package that play a smaller role - for more information on those, see =simulation.README.org=.

** Control
This package manages the decision-making processes for the RL agent.

- =Cutter.py=

  Defines the 'Cutter' class, which handles the specifics of the cutter's actions and movements within the simulation environment.

- =GymEnv.py=

  Implements a wrapper around the =simulation.Simulation= class, providing an API compatible with OpenAI's gymnasium environment specifications.
  
** Resources
This package contains static resources and configuration files used throughout the projects.

- =settings.json=

  The main configuration file for the project. It defines various settings and parameters used by different modules, such as simulation parameters and agent hyperparameters. It is recommended to back up this file before making any changes.

- =settings.json.bkp=

  A backup of the main configuration file.

- =settings.org=

  Documentation for the settings and configuration values used in the project.

** Tests
This package includes unit tests and integration tests for the project. These are primarily qualitative.

