* CGSAR RL

This project is an exploration of Reinforcement Learning (RL) concepts as they apply to U.S. Coast Guard Search and Rescue (SAR).

* Background
...
* Project Structure
This project is broken into modules, each handling seperate responsibilities and serving a different purpose.

** Application
This module handles application level configuration and logging. In the future, if we reach the point where we create a GUI or some form of desktop application to interface with the rest of this project, it will be placed in this module. For now, the application module is home to two primary classes:

- =config.py=
  
  Defines the "Config" class, which most other classes in this project use to read, write, and interact with a central JSON configuration file.
  
- =logger.py=

    Defines the "Logger" class, which most other classes in this project use to save and display log messages. These logs are written to STDOUT as well as external log files, which are stored in the 'data/logs' directory.


This module also contains two standalone scripts, which are used primarily for debugging:
- =logview.py=
  
  Displays a simple tkinter window that should be helpful for perusing log files produced by this project. Note that the script is /specifically/ intended for the log format produced by this code, so this is /not/ a general purpose log viewer.
  
- =performance_profile.py=
  
  Runs a really simple wrapper around the simulation's =wrapper.py= file. Intended as a profile for the simulation environment. This profile has nothing to do with the RL portion of this project, it is simply intended to analyze the physical simulation environment.


** Simulation
This module is the most complex portion of this project, and is intended to serve as a simulation environment within which to run an RL agent. There are a variety of classes defined here, with the =Simulation= class serving as the main entry point.

- =Simulation.py=

  The main entry point to the =simulation= module. Wraps calls to the =Environment= and =VictimGroup= classes to define an ocean environment with surface currents, wind, and a group of 'people' drifting in the water.

- =Environment.py=

  This class handles the environmental data, wrapping calls to =CurrentFetcher.py=, =DepthFetcher.py=, and =WindFetcher.py= to pull and store currents, wind, and depth data. This information is stored in =xarray= datasets.

** Control

** Resources

** Tests

