* Simulation

This module houses the main simulation logic; the environment that we built for our RL agent to run in. It is comprised of several components that each handle their own portion of the simulation logic.

/Note/: All references to the configuration file here are for convenience only. For more details on configuration values, see the =settings.org= file in the =resources= directory.

* Sub Modules
** Environment
The 'Environment' class handles environmental data. It is responsible for storing, updating, and low-level parsing of wind data, surface currents, and depth. It calls designated 'Fetcher' classes that download this information from the internet to local files.

Input Arguments:
- =lat=: the latitude of the center point
- =lon=: the longitude of the center point
- =config_path=: the path to the JSON config file. In this application, it is =resources/settings.json=.
- =margin=: the margin in miles from the center point. If 0, then the value from the configuration file is used.
- =date=: the initial date. If undefined, will grab a random date. Date must be within the range defined in the configuration file (=application.data.time_range_start= and =application.data.time_range_end=).


Useful Functions:
- =CurrentData=: Fetch the surface current data for the current date, within the environment's bounds.
- =DepthData=: Fetch depth data for the area within the environment's bounds.
- =WindData=: Fetch wind data for the current data, within the environment's bounds.
- =Update=: Update surface current, depth, and wind data. Takes a 'date' argument which will update the environment's current date.
- =Query=: Return a dictionary with the net wind velocity vector, and net current velocity vector at a point. Will interpolate if between defined data points. This function has been deprecated in favor of the =VectorizedQuery= function, but will remain available for convenience.
- =DepthQuery=: Takes =lat= and =lon= argument, returns the nearest depth value at that point.
- =VectorizedQuery=: Return a dictionary with the net wind velocirt vector and net current velocity vector at a *list of points*. Will interpolate. This function is optimized to run on arrays of data, and is significantly faster than the standard =Query= function for large numbers of query points. It is /strongly/ recommended to use =VectorizedQuery= in place of =Query= if you need to query for more than one point.

** VictimGroup
The 'VictimGroup' class represents a group of people floating in the ocean. This class handles the physical simulation of an object in water, calculating velocity and position. 'Victims' are represented as circular ellipsoids in 3-Dimensional space, though this distinction is not particularly relevant since force is not calculated directly.

Input Arguments:
- =x=: the horizontal minor axis, in meters. X and Y should be equal.
- =y=: the lateral minor axis, in meters. X and Y should be equal.
- =z=: the major axis.
- =lat=: Initial position. Latitude.
- =lon=: Initial position. Longitude.
- =victim_type=: The type of victim. Must be one of the allowed types (defined in the class file). Currently only 'piw' (person in water) and 'piw_lj' (person in water with lifejacket) are allowed.
- =env=: 'Environment' object.
- =config_path=: Path to the JSON configuration file.

/Note/: All arguments save =env= and =config_path= are *Lists*. The VictimGroup class is optimized to operate on a large number of victims at once, so you must pass in a list, where /order matters/, of all specifications. These lists are indexed relative to each other, so when passing in (for example), =lat= and =lon=, two victims (one at (x,y) and another at (a,b)) would look like =lat = [x,a]=, and =lon = [y,b]=.

/Note/: The victim's position updates occur at a different rate from the rest of the simulation. This is because physical calculations are only accurate over a time range of a few seconds at most. For every simulation tick, a victim will update at a rate defined by values in the configuration file.

Useful Functions:
- =update=: Calculates the number of steps to run, and for each step calculates the net velocity at every point in the group. Randomly applies noise to velocities, and updates position.
- =all_points=: Returns the position of every point in the cloud. This is deprecated, and will be removed soon. In its place, you can run =numpy.column_stack((VictimGroup.lats, VictimGroup.lons))=.
  
** Simulation
The 'Simulation' class is the main interface for the 'Simulation' module. It acts as a wrapper around the 'Environment' and 'Victim' classes, simulating ocean currents, wind vectors, and an object's movement through them both.

Input Arguments:
- =lat=: The latitude of the center point.
- =lon=: The longitude of the center point.
- =config_path=: The path to the JSON configuration file.
- =start_date=: The date to start the simulation at. Must be within the time range defined in the configuration file.
- =end_date=: The date to end the simulation. Must be within the time range defined in the configuration file.
- =frame_dir=: Directory to save output data to. Defaults to "data/frames".

/Note/: the deprecated =time_step= argument has been replaced by the =environment.settings.simulation_timedelta_minutes=, which applies only to the rate at which the environmental data will update. The physical simulation and dynamics calculations are handled seperately, inside the =Victim= class. The rate at which a victim's position/velocity etc will update is dependent on the value for =environment.settings.victim_timedelta_seconds= in the configuration file.


Useful Functions:
- =_add_victim_group=: Adds a =VictimGroup= object to the simulation.
- =Tick=: Advances the simulation by one time step.
- =Run=: Runs the simulation, saving all data to a timestamped file in =frame_dir=.


** Visualizer
The 'Visualizer' object is the primary method for visualizing the data output by the simulation. It is called entirely independently from the simulation class, pulling and visualizing data from the files the Simulation class outputs. This means that you can pregenerate data, and visualize it at a later date.

Input Arguments:
- =hdf5_file=: The path to the data file to visualize.

  
Useful Functions:
- =_load_trackline=: Allows the user to interactively load a 'trackline'. This comes from the =control.Cutter= class, and will typically look like '=Visualizer._load_trackline(Cutter.path)='. This is the /only/ way to visualize a generated trackline, and /must/ be called directly - the Visualizer object cannot be initialized with a trackline.
- =run=: Takes a boolean =show= argument, and =file= argument. The two are mutually exclusive, where =show= takes precedence. =show= indicates whether to visually display a Matplotlib plot. This plot is interactive, and can be manipulated for real-time analysis and easier examination than an .mp4 file. If =show= is false, the =run= method will export to an .mp4 file defined by the =file= argument, which defualts to './test.mp4'.
